### ISSUE TITLE
Portal seems to have changed

### ISSUE THREAD

**Issue by gingerbeardman** [s4l1h/bt-wifi-auto-login#2]
app_login_check_keyword is no longer matched.

**Comment by s4l1h** [comment]
@gingerbeardman 

I have just checked the keyword and it's still working. _**now logged on to BT**_
You can change the keyword in config file. (Log in the panel manually and find a keyword)

app_login_check_keyword=now logged on to BT
app_login_check_url=https://www.btwifi.com:8443/



_**My console log is;**_

Config details
post_password : "*******"
app_login_check_timer : "30"
app_login_url : "https://www.btwifi.com:8443/ante?partnerNetwork=btb"
app_login_check_url : "https://www.btwifi.com:8443/"
header_Referer : "https://www.btwifi.com:8443/home"
header_Origin : "https://www.btwifi.com:8443"
post_username : "************"
post_xhtmlLogon : "https://www.btwifi.com:8443/ante"
app_ignore_bad_ssl_error : "1"
app_login_check_keyword : "now logged on to BT"
Ignoring bad ssl error: ON
You are not logged on to BT
You're logged on to BT Wi-Fi
Setting up background login check every 30 seconds

**Comment by gingerbeardman** [comment]
Indeed the tool works but when I visit the portal address it doesn't contain that text. Weird.
